import Head from 'next/head'
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import axios from 'axios';
import cookie from "cookie"
import AdminOrders from '../components/screens/AdminOrders';
import AdminItems from '../components/screens/AdminItems';
import AdminCategories from '../components/screens/AdminCategories';


export default function Admin({role, userData}) {
    console.log(userData)
    const router = useRouter();

    const [screen, setScreen] = useState("orders")
    const [orders, setOrders] = useState(null)
    const [items, setItems] = useState(null)
    const [categories, setCategories] = useState(null)

    const fetchCategories = () => {
        axios.get("http://localhost:5277/api/categories", {headers: {Authorization: localStorage.getItem("token")}})
        .then(res => {
            console.log(res)
            setCategories(res.data)
        })
        .catch(err => console.log(err))
    }
    useEffect(() => {
        fetchCategories()
    }, [])

  return (
    <>
      <Head>
        <title>Admin Paneli</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex min-h-screen' >
        <div className='border-r font-medium shadow-xl bg-white z-20 border-gray-200 px-4 pt-8 flex flex-col gap-4' >
        <div className='flex flex-col gap-4'>
            <div
            className="hover:bg-gray-100 cursor-pointer rounded-md px-4 py-2"
            onClick={() => setScreen("orders")} >
                Siparişler
            </div>
            <div
            className="hover:bg-gray-100 cursor-pointer rounded-md px-4 py-2"
            onClick={() => setScreen("items")}>
                Ürünler
            </div>
            <div
            className="hover:bg-gray-100 cursor-pointer rounded-md px-4 py-2"
            onClick={() => setScreen("categories")}>
                Kategoriler
            </div>
        </div>
        <div
            className="hover:bg-gray-100 text-red-600 cursor-pointer rounded-md px-4 py-2"
            onClick={() => {
                localStorage.setItem("token", "")
                axios.get("http://localhost:3000/api/logout")
                    .then(router.push("/giris"))
                    .catch(err => console.log(err))
            } }>
                Çıkış Yap
            </div>
            </div>
        <div className='p-10 text-sm w-full bg-gray-50'>
        {
            screen === "orders" ? (
                <AdminOrders orders={orders} setOrders={setOrders} />
            ) : null
        }

        {
            screen === "items" ? (
                <AdminItems items={items} setItems={setItems} categories={categories} />
            ) : null
        }

        {
            screen === "categories" ? (
                <AdminCategories categories={categories} fetchCategories={fetchCategories} />
            ) : null
        }
      </div>
        </div>

    </>
  )
}

export async function getServerSideProps(context) {
  try {
    let userData = {}
    let role = ""

    const token = cookie.parse(context.req.headers.cookie).Authorization
    await axios.post("http://localhost:5277/api/auth/check",{}, {headers: {Authorization: token}})
    .then(resp => {
        role = resp.data.role
        resp.data.claimlist.forEach(claim => {
            userData = {...userData, [claim.type]: claim.value}
        })
     })

    if (role === "customer") throw '/';
    if (role === "admin") return {
      props: {role, userData},
    };

    throw "/giris"
  
    } catch (err) {
      console.log(err)
    if (err === '/' || err === '/giris')
      return {
        redirect: {
          permanent: false,
          destination: err,
        },
      };
      else {
        return {
        redirect: {
          permanent: false,
          destination: "/giris",
        },
      };
      }
  }
}
